# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      -  main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@v2
#step 2      
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
#step 3        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
#step 4
    -   name: run tests
        run: pytest
       
